spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

logging:
  level:
    at.fhtw.grantscout: debug

scraping:
  interval_minutes: 60

openai:
  key: ${OPENAI_API_KEY}