services:
  db:
    image: postgres:15
    container_name: grantscout-db
    environment:
      POSTGRES_DB: grantscout-scraping
      POSTGRES_USER: gs
      POSTGRES_PASSWORD: Password12345678
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: